Handing error for jenkins file

diff --git a/src/test/resources/Jenkins/Jenkinsfile-selenium-grid b/src/test/resources/Jenkins/Jenkinsfile-selenium-grid
--- a/src/test/resources/Jenkins/Jenkinsfile-selenium-grid
+++ b/src/test/resources/Jenkins/Jenkinsfile-selenium-grid
@@ -7,6 +7,10 @@ pipeline {
             steps {
                 script {
                     status = sh (script:''' sshpass -p qwerty11 ssh -o StrictHostKeyChecking=no administrator@192.168.0.142 "mkdir -p ~/jenkinsjob/seleniumgrid" ''', returnStatus:true)
+                     if (status != 0) {
+                        echo "Fail to create folder"
+                        sh(''' exit 1 ''')
+                    }
                 }
             }
         }
@@ -14,6 +18,10 @@ pipeline {
             steps {
                 script {
                     status = sh (script:''' sshpass -p qwerty11 scp -o StrictHostKeyChecking=no src/test/resources/docker/docker-compose-selenium-grid.yml administrator@192.168.0.142:~/jenkinsjob/seleniumgrid ''', returnStatus:true)
+                     if (status != 0) {
+                        echo "Fail to copy compose file"
+                        sh(''' exit 1 ''')
+                    }
                 }
             }
         }
@@ -21,14 +29,8 @@ pipeline {
             steps {
                 script {
                     status = sh (script:''' sshpass -p qwerty11 ssh -o StrictHostKeyChecking=no administrator@192.168.0.142 "sshpass -p qwerty11 sudo docker-compose -f ~/jenkinsjob/seleniumgrid/docker-compose-selenium-grid.yml up -d" ''', returnStatus:true)
-                }
-            }
-        }
-        stage("status code") {
-            steps {
-                script {
-                    if (status != 0) {
-                        echo "Fail"
+                     if (status != 0) {
+                        echo "Fail to start compose file"
                         sh(''' exit 1 ''')
                     }
                 }
